### Create a new order
POST http://localhost:3001/orders
content-type: application/json

{
  "user_id": 1,
  "products": [
    {"id": 1, "quantity": 12 },
    {"id": 2, "quantity": 1 }
  ]
}

### List all orders
GET http://localhost:3001/orders?status=false

### List all orders by user id
GET http://localhost:3001/orders/users/1?status=false

### Show order by id
GET http://localhost:3001/orders/2


### Update order status
PATCH http://localhost:3001/orders/status/1
content-type: application/json

{
  "status": true
}

### Delete order by id
DELETE  http://localhost:3001/orders/3